-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 26-08-2018 a las 03:12:12
-- Versión del servidor: 10.1.28-MariaDB
-- Versión de PHP: 7.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `horoscopo`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `signo`
--

CREATE TABLE `signo` (
  `id_signo` int(2) NOT NULL,
  `nombre` varchar(50) COLLATE ucs2_spanish_ci NOT NULL,
  `personalidad` text CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `color` varchar(40) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `elemento` varchar(10) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `simboliza` text CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `semanal` text CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=ucs2 COLLATE=ucs2_spanish_ci;

--
-- Volcado de datos para la tabla `signo`
--

INSERT INTO `signo` (`id_signo`, `nombre`, `personalidad`, `color`, `elemento`, `simboliza`, `semanal`) VALUES
(1, 'Leo', 'Leo es el signo más dominante del zodiaco. Son encantadores y atractivos, hay algunos que dicen que incluso adictivos y esto les hace algo peligrosos. Son líderes natos, creativos y extrovertidos, pero también bastante egocéntricos, a veces incluso prepotentes, lo que hace que siempre quieran ser el centro de atención.', 'Naranja y dorado', 'Fuego', 'a energía, la creatividad, los juegos, las especulaciones, el orgullo, la vanidad, la realeza, la diversión, los deportes, los espectáculos, la niñez, la educación, la elevación, la gloria, la fama, el poder.', 'Puedes tener un periodo importante tanto en lo romántico, como en las amistades. Inicias un periodo estupendo para recargar pilas ya que tu energía volverá a ser muy fuerte, pero trata de centrarte y no quieras acudir en pos de todo: amor, salud, trabajo, deseos. Dale a cada cosa su tiempo. Tendrás una semana de cierta tranquilidad en la que tenderás a tener todo de manera estable, posiblemente los astros todavía te favorecen. En cuanto a los afectos, los que tengan pareja lo tendrán muy positivo, pero los que no las cosas seguirán como estaban sin ser el momento adecuado para formalizar relaciones, tendrás que esperar un poco más de tiempo. Mejor día 20 y 26.'),
(2, 'Virgo', 'Los virgo son observadores y pacientes, a veces pueden incluso parecer fríos y esto hace que les cueste hacer amigos. Son metódicos y estudiosos, razonan de manera muy lógica, pero sin embargo les cuesta llegar a una solución firme. Si nos fijamos en la personalidad del hombre según su signo, son los más cariñosos y los mejores maridos.', 'Verde limón y marrón', 'Tierra', 'La búsqueda de la perfección, la crítica, el análisis, la lógica, el sistema, la laboriosidad, el detalle, las ocupaciones subalternas, el proletariado, el servicio, la salud, las artesanías, la eficiencia, las fábricas, los animales domésticos.', 'Estarás con una gran agitación y movimiento, en todas las direcciones con tendencia a los nervios. Será muy proclive a que hagas una reflexión en tu interior que haga mella por la necesidad de encontrar soluciones a asuntos que consideras que no tienes bien equilibrados en tu vida. Tendrás un ritmo que se va normalizando tanto en el trabajo y más aún en la economía. No sería de extrañar, si tienes negocio propio, el que buscaras complementar con alguien que compartir el esfuerzo, aportando un capital para realizar mejores inversiones y trabajar mejor. De todas las formas podrás disfrutar de una semana muy feliz y próspera en muchos aspectos. Mejor día 24 y 25.'),
(3, 'Libra', 'Es el signo más civilizado, amables y pacíficos, elegantes y conciliadores, esto hace que no soporten bien el conflicto y la crueldad. Sin embargo, si les sacas de quicio o te metes con ellos, pueden dejarte llorando. Su mayor defecto es que son algo frívolos y muchas veces poco leales.', 'Rosado y colores pasteles', 'Aire', 'La justicia, la equidad, el equilibrio, el principio complementario, los acuerdos, las relaciones, la belleza, la cultura artística, la armonía, el refinamiento, el otoño, la diplomacia, los contratos.', 'Si quieres seguir estando en armonía con tu pareja, debes agradecer su cariño y abnegación de lo que hace por ti, también va encaminado a los amigos, la libido estará bastante fuerte en este periodo, procura no correr riesgos innecesarios, si tomas otro camino diferente a  tu relación normal, se puede volver en tu contra, pues parece que el amor a primera vista te asalta, y no es conveniente en este momento, aunque sabes que tienes cierto encanto y que te gusta correr riesgos, no debes precipitarte porque a lo mejor no sales nada bien en el invento y podrías romper una relación muy sólida. Tiempo de la amistad, todo el mundo se acuerda de ti. Mejor día 21 y 22.'),
(4, 'Escorpión', 'Misteriosos y seductores, son muy intensos y si consiguen enfocar toda su energía de manera constructiva, son personas muy valiosas. También es cierto que está entre los signos del zodiaco más rencorosos, por no decir que es el más rencoroso de todos. Es muy crítico no solo con los demás, sino también consigo mismo.', 'rojo oscuro, verde botella', 'Agua', 'La transmutación, la renovación, el cambio, lo misterioso, las fuerzas ocultas, la magia, la muerte, la destrucción y la regeneración, las confrontaciones, la lucha, los retos, los peligros de sumerción, los dramas pasionales, las envidias, las herencias, los legados, las donaciones, las búsquedas difíciles, la interiorización, el inconsciente colectivo, el sueño.', 'Será muy interesante que te dejes asesorar por personas en las que confías acerca de los temas que más te preocupan en este momento. No cometas ningún exceso, ni de comida ni en el trabajo, porque tendrás tendencia hacia ello y si tienes que desplazarte, tómalo con mucha clama ya que las prisas no son nada aconsejables. Ten prudencia. Harás un rápido progreso hacia tus objetivos, destacará tu interés por los estudios ocultos la transformación y reinversión personal. Gozarás de una excelente salud, pero se te recomienda, trata de descansar más y hacer algún tipo de deporte para descargar la adrenalina acumulada. Mejor día 20 y 26.'),
(5, 'Sagitario', 'Uno de los signos más positivos, les encanta la aventura y lo desconocido. Espontáneos y atractivos, pero también impacientes y de fuerte temperamento. Creen en la ética y la honestidad y esto hace que a veces pequen de ser demasiado sinceros. Son capaces de sacrificarse por sus amigos y esto hace que a veces sean demasiado exigentes con ellos.', 'Azul aguamarina, violeta', 'Fuego', 'Los viajes largos, los países extranjeros, la filosofia, las leyes, la religión, los altos cargos eclesiásticos, la profecia, la mente abstracta, las aventuras, el comercio con el extranjero, la navegación intercontinental, la vida al aire libre, los ejercicios físicos, las carreras de caballos, la velocidad, las apuestas, los sabios, los estudios superiores, la independencia.', 'Continúa con lo que se te dijo en semanas pasadas, trata de continuar con tu ejercicio habitual, te pondrás en forma y llevarás un estilo de vida sano, ya sabes lo que cuenta para ti la energía y si continúas así la obtendrás. Procura estar optimista y alegre, pero no de cara a la galería si no en lo más intimo de tu ser. Sabemos que tu simpatía y tu buen talante, te pueden atraer el éxito, pero no intentes cambiar las condiciones que se te presentan, debes adaptarte a ellas lo mejor posible y en un futuro próximo llegará el momento de lanzarte a ello. No es recomendable el hacer grandes viajes, si antes no has tomado las suficientes medidas. Mejor día 21 y 22.'),
(6, 'Capricornio', 'Agradables, inteligentes y justos. Son además trabajadores, responsables y muy estables. Sin embargo, pueden tender a la excesiva melancolía e incluso rozar la depresión. Prefiere tener pocos amigos, pero sabe bien cómo conservarlos, gran amigo y consejero. Les cuesta ser felices en sus relaciones de pareja ya que son bastante celosos.', 'Negro y azúl oscuro', 'Tierra', 'La política, la tierra, los lugares elevados, las montañas, las cimas, los lugares aislados e inaccesibles, las luchas, los obstáculos e impedimentos, el karma, la mala suerte, los reveses de fortuna, las carreras brillantes, la decadencia, el tiempo, la noche, los viejos, las deformidades, el invierno, el frio, las minas, el deber cívico, las ambiciones profesionales.', 'Trata de recuperar cualquier espíritu de juego y aventura que te haga sentirte con los pies en la tierra.  No dejes de sentirte como esa persona infantil que todos llevamos dentro, somos casi incapaces de experimentar la alegría que ellos llevan. Continuarás preguntándote si lo que has hecho es lo que realmente necesitas para sentirte a gusto. Si la respuesta es afirmativa, sigue adelante pese a todas las oposiciones que puedas tener, si es negativa, o encuentras matices mejorables, entonces debes escuchar los consejos de los otros y sigue lo que te parezca de mayor sentido común. En la salud cuida de no sobrepasarte en los límites permitidos por tu cuerpo. Mejor día 25 y 26.'),
(7, 'Acuario', 'De personalidad muy fuerte, galante y conquistador. Son muy inteligentes e innovadores, capaces de expresarse de manera muy lógica y sin perder el humor. Es uno de los signos más tolerantes, pero no le engañes o conocerás su furia. Sus mayores defectos son la excentricidad y la falta de seriedad en muchas ocasiones.', 'Violeta, gris', 'Aire', 'La amistad, la sed espiritual, las fraternidades, el amor universal, el esfuerzo colectivo, los sindicatos, las revoluciones, el altruismo, el humanitarismo, el progreso, la tecnología, la cibernética, la robótica, la aviación, la electrónica, la medicina alternativa, la radiestesia, lo mental, la vibración, el ritmo, lo novedoso, los inventos, lo inconvencional, la libertad, las sociedades de cooperación y mutua ayuda, las cámaras de representantes, la democracia, la solidaridad, la unión de los pueblos.', 'Si trabajas en temas que tengan que ver con el arte, podrás tener más éxito que el acostumbrado, si no es a sí, trata de explorar sobre esta línea que te resultaría bastante ventajoso. Tendrás una nueva energía que te dará un impulso para tu salud. Estas entrando en un proceso de creatividad y explorar las alegrías que te ofrece la vida, por lo que, teniendo tu economía bastante estable, te puedes permitir dedicarte un poco más al ocio. Notarás como en salidas de ocio, teatro, cine, cenas en las que puedas pasar un buen rato es donde más a gusto te encontrarás. Una fuerte dosis de iniciativa y optimismo para afrontar cualquier obstáculo.  Mejor día 24 y 25'),
(8, 'Piscis', 'Pacientes y tranquilos, muy amables y sensibles, son capaces de lidiar de manera muy serena y reconfortante con los problemas de los demás, pero, sin embargo, puede resultar bastante egoísta y no siempre le apetece. Se guía más por las emociones que por la razón. A veces es un poco exagerado y no siempre está muy centrado en la realidad que le rodea.\r\n', 'Azul mar', 'Agua', 'Los océanos, las cosas móviles, variables, cambiantes, la hospitalidad, la bebida, el vicio, el dismulo, los engaños, la pérdida de reputación y de la libertad, los hospitales, las cárceles, las casas de reposo, los asilos, la filantropía, las instituciones piadosas, los dispensarios, las sociedades protectoras de animales, las traiciones, los suicidios, las dependencias, el escapismo, los trabajos aislados, las ciencias ocultas, las maniobras sediciosas, el espionaje, el camuflaje, la hipocresía, el martirio, el sacrificio, el servicio, el inconsciente colectivo.', 'Trata de descansar y relajarte un poco más, podrás estar algo pendiente por la salud de una persona allegada, pero piensa que la armonía no solamente es un factor importante para tu vida. Tendrás cambios muy positivos en tu profesión y vida en general. Estarás muy audaz en el tema económico, pero si tienes que aceptar contratos no los firmes antes de fin de semana. Si tienes que comunicarte con la persona amada, trata de ser muy locuaz y no de buscar rodeos, ve al grano y directamente, ya que puede haber mala interpretación en tus actos y palabras que te pueden pasar factura más adelante. Para no tener interferencias con socios, lo mejor estar en solitario. Mejor día 22 y 26.'),
(9, 'Aries', 'Adorables y muy divertidos, llenos de energía y entusiasmo. Les encantan los retos y empezar cosas nuevas, pero no les gusta recibir órdenes, esto hace que a veces sean egocéntricos, impulsivos y autoritarios. Muy independientes y dispuestos a arriesgarse, pero también algo frenéticos y alérgicos al compromiso.', 'Rojo', 'Fuego', 'los comienzos, el principio, la mañana, la primavera, los animales carnivoros, los jefes, el mando, la fuerza, la violencia, el impulso, la autoridad, la virilidad, la juventud, las armas, los accidentes en la cabeza, peligro por el hierro, el fuego y las armas.', 'Para muchos nativos del signo será un momento de mucho movimiento, así que debes tener cuidado con el estrés, ya que es un momento tradicionalmente de vacaciones, pero para muchas personas será de gran movimiento, tendrás que dar mucho y bueno ya que vas a querer aprovechar las oportunidades que la época te brinda. Aun así, deberás cuidar un poco la salud para evitar caer en el estrés antes citado, así que cuídate un poco el sistema nervioso y relájate lo que puedas. Piensa que tienes una magnifica oportunidad, por lo que conseguirás amor y lucha, comodidad y acción, esta conjunción es muy interesante para poder mejorar. Mejor día 25 y 26.'),
(10, 'Tauro', 'Son prudentes, muy estables y con gran fuerza de voluntad. Tienen muy desarrollado el sentido de la justicia y tienden a ayudar a quien lo necesita. A veces son demasiado tercos y complejos, lo que hace que sea difícil controlar su lado más colérico. Son fieles y leales, pero igualmente celosos y un poco posesivos.', 'Verde', 'Tierra', 'La fuerza de voluntad, la permanencia, la firmeza, la perseverancia, la estabilidad, la concreción, la resistencia, la fuerza, la sensualidad, la buena mesa, la forma, la música, el talento vocal, los sentimientos duraderos, la naturaleza, la agricultura, la banca.', 'La economía se te ve bastante saneada o en vías de total recuperación, continúa atendiendo a tu imagen y tu placer personal. Gozas de buena salud y sería muy interesante que practicaras algún tipo de deporte, te sentaría estupendamente. Evita en lo posible la mala alimentación, así como bebidas alcohólicas. Tus acciones acabarán dando frutos y produciendo excelentes resultados si actúas desde la madurez y no traicionas tu proceso personal, se trata sobre todo en trabajar en ti, en tu forma de ser, tus proyectos, verás como los nuevos enfoques te harán avanzar muchísimo., revisa y reflexiona sobre todo lo que has hecho últimamente. Mejor día 21 y 22.'),
(11, 'Géminis', 'Su carácter puede resultar complejo y algo contradictorio, se mueven un poco en la ambigüedad. Pueden ser amables y generosos, pero son capaces de mentirosos y manipuladores. Empiezan cada nuevo proyecto con mucho entusiasmo, pero se desaniman con facilidad. Suelen tener muchos conocidos, pero pocos buenos amigos.', 'Amarillo', 'Aire', 'El elemento aéreo, las comunicaciones, la dualidad, la iniciativa en los negocios, el comercio, el trabajo intelectual, los viajes, los hermanos, los amigos de la infancia, los escritos, los idiomas, la mente concreta.', 'Se te puede presentar una oportunidad única y especial lo que te permitirá cuidarte y mimarte. Entras a la vez en un periodo de mucha independencia personal. Trata de controlarlo bien para que te de buenos resultados. Tendrás muchas posibilidades de estrechar relación y comunicación con la familia, hermanos y amistades, que a la vez son como hermanos, para afrontar decisiones con respecto a otros miembros de más edad con estados de impotencia o de alguna enfermedad. Continuará la buena marcha positiva, aunque podrás hacerte cargo de otra ocupación administrativa relacionado con algo familiar. Podrías tener algún problema de papeleo.   Mejor día 20 y 26.'),
(12, 'Cáncer', 'Es la personalidad más rara de todo el zodiaco, cuanto menos desconcertante. Pueden ser muy tímidos, incluso aburridos y de repente sacar un lado fascinante y de lo más interesante. A veces puede parecer algo limitado, pero son capaces de ponerse en el sitio del otro y resolver cualquier situación.', 'Blanco, nacarado y plateado', 'Agua', 'La maternidad, los partos, el amor maternal, la familia, la patria, la casa, la cocina, las masas, las mujeres, los ríos, el sentimiento, la imaginación.', 'Si estas en temas que requieran cierta legalidad y piensas en mandarlo todo a paseo, ten calma, en todo caso no te precipites en las apreciaciones de la situación. Sigues en una situación estupenda para tus expectativas de futuro y asuntos profesionales, aprovecha esta oportunidad para entrar en una nueva dinámica en estos asuntos. Trata de huir de las situaciones tensas que se puedan producir a tu alrededor, ya que puedes perder los estribos con mucha facilidad y dada tu actividad frenética en estos momentos, no te conviene para nada, no darías buena imagen el tu entorno. Cuidado con las malas digestiones, que pueden estar producidas por el estrés. Mejor día 21 y 22.');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `signo`
--
ALTER TABLE `signo`
  ADD PRIMARY KEY (`id_signo`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `signo`
--
ALTER TABLE `signo`
  MODIFY `id_signo` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
